# Generated by Django 6.0.5 on 2026-05-27 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_orders_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='roduct',
            new_name='product',
        ),
    ]
