# Generated by Django 6.0.5 on 2026-06-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_orders_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='c_price',
            field=models.IntegerField(),
        ),
    ]
