# Generated by Django 6.0.5 on 2026-06-15 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wishlist',
        ),
    ]
