# Generated by Django 6.0.5 on 2026-08-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='alt_phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
